//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelloServiceConsoleClient.HelloService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="HelloService.IHelloService")]
    public interface IHelloService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHelloService/Ping", ReplyAction="http://tempuri.org/IHelloService/PingResponse")]
        string Ping(string message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHelloService/Ping", ReplyAction="http://tempuri.org/IHelloService/PingResponse")]
        System.Threading.Tasks.Task<string> PingAsync(string message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHelloService/Send", ReplyAction="http://tempuri.org/IHelloService/SendResponse")]
        void Send(string content);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHelloService/Send", ReplyAction="http://tempuri.org/IHelloService/SendResponse")]
        System.Threading.Tasks.Task SendAsync(string content);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IHelloServiceChannel : HelloServiceConsoleClient.HelloService.IHelloService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HelloServiceClient : System.ServiceModel.ClientBase<HelloServiceConsoleClient.HelloService.IHelloService>, HelloServiceConsoleClient.HelloService.IHelloService {
        
        public HelloServiceClient() {
        }
        
        public HelloServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HelloServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HelloServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HelloServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Ping(string message) {
            return base.Channel.Ping(message);
        }
        
        public System.Threading.Tasks.Task<string> PingAsync(string message) {
            return base.Channel.PingAsync(message);
        }
        
        public void Send(string content) {
            base.Channel.Send(content);
        }
        
        public System.Threading.Tasks.Task SendAsync(string content) {
            return base.Channel.SendAsync(content);
        }
    }
}
